### ISSUE TITLE
Many mobile nodes work in a mesh network, is it possible cause network congestion?

### ISSUE THREAD

**Issue by dodolzg** [virl/underdark-android#2]
Sorry, the question is not bug.
I am curious of what if many mobile nodes work in a mesh network, and underdark use broadcast mechanism to send file or message via Bluetooth, is it possible cause network congestion?

**Comment by virl** [comment]
@dodolzg Thanks for the question!
Underdark currently doesn't use broadcast for Bluetooth, it uses system API for RFCOMM Bluetooth connection between nodes. Of course it is the "broadcast" in the sense that amount of channels is limited.

But range of Bluetooth is relatively short, so I don't think the network congestion practically possible (because nodes will not be located so tightly in so short range).

In mesh network there is a different problem called "broadcast storm": when many nodes simultaneously send broadcast packets to entirety of mesh network (broadcast not in Bluetooth sense, but in the sense that packet must be re-routed to each node in mesh network). That problem is mitigated by advanced routing algorithms.

I'm currently implementing routing into the library itself and working on more advanced example code in the form of the chat app.

**Comment by dodolzg** [comment]
Thanks a lot !
You mentioned that you are implementing routing into the lib, so if A connect with B , B connect with C, A and C is not connected cause the distance is beyond the range of Bluetooth, does that mean that A can't send message to C right now?

**Comment by virl** [comment]
@dodolzg Such routing is already implemented in my demo apps in stores (see links at http://underdark.io), but it isn't in the lib currently. It is not complex at all, it's I just decided that library must be able to do it too. I'll commit the example chat app (with sources) that will demonstrate using it.

**Comment by dodolzg** [comment]
Excellent! Thanks!
